// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v7.36.2
// source: paratxindex.proto

package types

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ParaTxIndexItem 区块内单笔平行链跨链交易的索引项
type ParaTxIndexItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 该交易在区块内该title全部平行链交易(过滤后)有序列表中的下标
	BaseIndex uint32 `protobuf:"varint,1,opt,name=baseIndex,proto3" json:"baseIndex,omitempty"`
	// 交易的action类型(ParacrossAction.Ty), 消费方据此跳过非资产转移类交易
	Ty int32 `protobuf:"varint,2,opt,name=ty,proto3" json:"ty,omitempty"`
	// 交易完整字节, 仅资产转移类交易(Ty为10000,10001或大于等于10005)记录
	Tx []byte `protobuf:"bytes,3,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (x *ParaTxIndexItem) Reset() {
	*x = ParaTxIndexItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paratxindex_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParaTxIndexItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParaTxIndexItem) ProtoMessage() {}

func (x *ParaTxIndexItem) ProtoReflect() protoreflect.Message {
	mi := &file_paratxindex_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParaTxIndexItem.ProtoReflect.Descriptor instead.
func (*ParaTxIndexItem) Descriptor() ([]byte, []int) {
	return file_paratxindex_proto_rawDescGZIP(), []int{0}
}

func (x *ParaTxIndexItem) GetBaseIndex() uint32 {
	if x != nil {
		return x.BaseIndex
	}
	return 0
}

func (x *ParaTxIndexItem) GetTy() int32 {
	if x != nil {
		return x.Ty
	}
	return 0
}

func (x *ParaTxIndexItem) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

// HeightParaIndex 主链区块内某个平行链title的跨链交易索引
// 用于跨链交易执行时避免读取历史区块体
type HeightParaIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 区块hash, 消费方据此校验索引与请求的区块一致
	Hash []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	// 过滤后平行链交易的总数, 即位图长度
	BaseHashCount uint32 `protobuf:"varint,4,opt,name=baseHashCount,proto3" json:"baseHashCount,omitempty"`
	// 按交易在区块内的顺序排列
	Items []*ParaTxIndexItem `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *HeightParaIndex) Reset() {
	*x = HeightParaIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paratxindex_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeightParaIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeightParaIndex) ProtoMessage() {}

func (x *HeightParaIndex) ProtoReflect() protoreflect.Message {
	mi := &file_paratxindex_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeightParaIndex.ProtoReflect.Descriptor instead.
func (*HeightParaIndex) Descriptor() ([]byte, []int) {
	return file_paratxindex_proto_rawDescGZIP(), []int{1}
}

func (x *HeightParaIndex) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *HeightParaIndex) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HeightParaIndex) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *HeightParaIndex) GetBaseHashCount() uint32 {
	if x != nil {
		return x.BaseHashCount
	}
	return 0
}

func (x *HeightParaIndex) GetItems() []*ParaTxIndexItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// ReqParaTxIndex 按高度和title请求平行链跨链交易索引
type ReqParaTxIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *ReqParaTxIndex) Reset() {
	*x = ReqParaTxIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paratxindex_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqParaTxIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqParaTxIndex) ProtoMessage() {}

func (x *ReqParaTxIndex) ProtoReflect() protoreflect.Message {
	mi := &file_paratxindex_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqParaTxIndex.ProtoReflect.Descriptor instead.
func (*ReqParaTxIndex) Descriptor() ([]byte, []int) {
	return file_paratxindex_proto_rawDescGZIP(), []int{2}
}

func (x *ReqParaTxIndex) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ReqParaTxIndex) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_paratxindex_proto protoreflect.FileDescriptor

var file_paratxindex_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x61, 0x72, 0x61, 0x74, 0x78, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x4f, 0x0a, 0x0f, 0x50, 0x61,
	0x72, 0x61, 0x54, 0x78, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1c, 0x0a,
	0x09, 0x62, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x62, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x74,
	0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x78, 0x22, 0xa7, 0x01, 0x0a, 0x0f,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x50, 0x61, 0x72, 0x61, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x12, 0x24, 0x0a, 0x0d, 0x62, 0x61, 0x73, 0x65, 0x48, 0x61, 0x73, 0x68, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x62, 0x61, 0x73, 0x65, 0x48, 0x61,
	0x73, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50,
	0x61, 0x72, 0x61, 0x54, 0x78, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x3e, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x50, 0x61, 0x72, 0x61,
	0x54, 0x78, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x33, 0x33, 0x63, 0x6e, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x33, 0x33,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_paratxindex_proto_rawDescOnce sync.Once
	file_paratxindex_proto_rawDescData = file_paratxindex_proto_rawDesc
)

func file_paratxindex_proto_rawDescGZIP() []byte {
	file_paratxindex_proto_rawDescOnce.Do(func() {
		file_paratxindex_proto_rawDescData = protoimpl.X.CompressGZIP(file_paratxindex_proto_rawDescData)
	})
	return file_paratxindex_proto_rawDescData
}

var file_paratxindex_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_paratxindex_proto_goTypes = []interface{}{
	(*ParaTxIndexItem)(nil), // 0: types.ParaTxIndexItem
	(*HeightParaIndex)(nil), // 1: types.HeightParaIndex
	(*ReqParaTxIndex)(nil),  // 2: types.ReqParaTxIndex
}
var file_paratxindex_proto_depIdxs = []int32{
	0, // 0: types.HeightParaIndex.items:type_name -> types.ParaTxIndexItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_paratxindex_proto_init() }
func file_paratxindex_proto_init() {
	if File_paratxindex_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_paratxindex_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParaTxIndexItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paratxindex_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeightParaIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paratxindex_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqParaTxIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_paratxindex_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paratxindex_proto_goTypes,
		DependencyIndexes: file_paratxindex_proto_depIdxs,
		MessageInfos:      file_paratxindex_proto_msgTypes,
	}.Build()
	File_paratxindex_proto = out.File
	file_paratxindex_proto_rawDesc = nil
	file_paratxindex_proto_goTypes = nil
	file_paratxindex_proto_depIdxs = nil
}
